#!/usr/bin/env bash
#This script displays all active IPv4 IPs on this machine

file="/etc/hosts"

touch filework

while read -r line; do

    if [[ "$line" == *.*.*.* ]]
    then
        echo "$line" >> filework
    fi

done <$file

cut -f1 -d ' ' filework

rm filework

