#!/usr/bin/env bash
#This script starts up a server at localhost of the current machine listening on port 98

touch hosts.new

echo "127.0.0.2   localhost" >> hosts.new

cp -f hosts.new /etc/hosts

rm hosts.new

nc -l localhost 98

